# 
# docker-compose.yml — определяет сервисы для разработки и тестирования.

#Что нужно сделать:
#  - Настроить сервисы для:
#      - PostgreSQL (или MySQL) с начальной базой.
#      - Приложения Spring Boot (если нужно).
#  - Открыть нужные порты (например, 5432, 8080).
#  - Настроить volume для хранения данных БД.

services:
  postgres:
    image: postgres:16
    restart: "no"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bankdb
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
volumes:
  postgres_data: